format = ''' Î» $directory$python$ocaml$docker_context â¯ '''

scan_timeout = 10
add_newline = false

[python]
symbol = 'ğŸ '
pyenv_version_name = true
style = 'green bold'

[ocaml]
format = 'via [ğŸª $version]($style) '
